version: "2.2"

services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000 # Cube.js API and Developer Playground
    environment:
      - CUBEJS_DB_TYPE=postgres
      - CUBEJS_DB_HOST=host.docker.internal
      - CUBEJS_DB_USER=cube
      - CUBEJS_DB_PASS=12345
      - CUBEJS_DB_NAME=ecom

      - CUBEJS_API_SECRET=SECRET
      - CUBEJS_DEV_MODE=true
    volumes:
      - ./backend:/cube/conf
  dashboard:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:4000/cubejs-api/v1
      - REACT_APP_CUBEJS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQ2NjY4OTR9.0fdi5cuDZ2t3OSrPOMoc3B1_pwhnWj4ZmM3FHEX7Aus
